
title: Dusto AI
description: Basic blog time
theme: jekyll-theme-cayman

# Site settings
url: https://dusto-ai.github.io
baseurl: "/dusto-ai"  # keep empty for user site (username.github.io). For project sites, set to "/repo-name".
permalink: /blog/:year/:month/:day/:title/

# Social (optional; show/hide in templates as you customize)
author:
  name: Dustin
  email: 
  github: dusto-ai
  linkedin: 
