
title: Your Name
description: A short tagline about you.
theme: jekyll-theme-cayman

# Site settings
url: https://dusto-ai.github.io
baseurl: ""  # keep empty for user site (username.github.io). For project sites, set to "/repo-name".
permalink: /blog/:year/:month/:day/:title/

# Social (optional; show/hide in templates as you customize)
author:
  name: Your Name
  email: you@example.com
  github: YOUR-USERNAME
  linkedin: your-linkedin-handle
